In [2]:
# multiple features -> single output
import numpy as np

weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)


0.9800000000000001


In [3]:
# single feature -> multiple outputs [hurt, win, sad]

weights = [0.3, 0.2, 0.9]

def ele_mul(number, vector):
    output = [0, 0, 0]
    
    assert len(output) == len(vector)
    
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

def neural_network(input, weights):
    return ele_mul(input, weights)

wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]

pred = neural_network(input, weights)
print(pred)


[0.195, 0.13, 0.5850000000000001]


In [5]:
# multiple features -> multiple outputs [# toes, % win, # fans] -> [hurt, win, sad]
weights = [[0.1, 0.1, -0.3], # hurt
           [0.1, 0.2, 0.0],  # win
           [0.0, 1.3, 0.1]]  # sad

def w_sum(a, b):
    assert len(a) == len(b)
    output = 0 
    for i in range(len(a)):
        output += a[i] * b[i]
    return output

def vect_mat_mul(vect, matrix):
    assert len(vect) == len(matrix)
    output = [0, 0, 0]
    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred


toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)
print(pred)


[0.555, 0.9800000000000001, 0.9650000000000001]


In [6]:
# 2-layer multiple features -> multiple outputs 
# [# toes, % win, # fans] -> [hurt, win, sad]
import numpy as np
ih_wgt = np.array([[0.1, 0.2, -0.1], # hid[0]
                  [-0.1, 0.1, 0.9],  # hid[1]
                  [0.1, 0.4, 0.1]])  # hid[2]

hp_wgt = np.array([[0.3, 1.1, -0.3], # hurt
                  [0.1, 0.2, 0.0],  # win
                  [0.0, 1.3, 0.1]])  # sad

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred
    
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)


[ 0.496  1.256 -0.286]


In [9]:
# basic numpy ops
import numpy as np

a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])
d = np.zeros((2, 4))
e = np.random.rand(2, 5)

print(c * 0.1)

[[0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]]
